<?php
/**
 * @author Botgento Team
 * @copyright Copyright (c) 2017 Botgento (https://www.botgento.com)
 * @package Botgento_Base
 */

/**
 * Copyright © 2017 Botgento. All rights reserved.
 */
?>
<span class="block" data-bind="scope: 'botgentoApi'" data-role="botgento-api"><span>
<script type="text/javascript">var bgc = ''; var bgc_uuid = ''; var setBgc = ''; var bgc_csrf = '';</script>
</span></span>
<script type="text/x-magento-init">
{"*": {"Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>}}
</script>
