<?php
/**
 * @author Botgento Team
 * @copyright Copyright (c) 2017 Botgento (https://www.botgento.com)
 * @package Botgento_Base
 */

/**
 * Copyright © 2017 Botgento. All rights reserved.
 */
?>
<div class="botgento-instock-alert" data-role="in-stock-alert" data-bind="scope: 'in-stock'" style="display: none;">
    <!-- ko if: v().status -->
    <p class="botgento-instock-alert-text"><?php echo __('Notify me when this product is back in stock'); ?></p>
    <div id="fb-loader" class="fb-loader" style="clear: both">
        <img src="<?php echo $this->getViewFileUrl('Botgento_Base::images/fb-loader.gif'); ?>"
             alt="<?php echo __('Please wait...'); ?>"
             title="<?php echo __('Please wait...'); ?>"
             class="v-middle" width="30px">
    </div>
    <div class="fb-send-to-messenger text-center"
        data-bind="attr: {
            class: 'fb-send-to-messenger text-center',
            messenger_app_id: v().app_id,
            origin : v().origin,
            page_id : v().page_id,
            'data-ref' : v().data_ref,
            color : v().color,
            cta_text : v().cta_text,
            size : v().size,
        }">
    </div>
    <!-- /ko -->
</div>
<script type="text/x-magento-init">
{"[data-role=in-stock-alert]": {"Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>}}
</script>
