<?php
/**
 * @author Botgento Team
 * @copyright Copyright (c) 2017 Botgento (https://www.botgento.com)
 * @package Botgento_Base
 */

/**
 * Copyright © 2017 Botgento. All rights reserved.
 */
?>
<?php
$helper = $this->helper('Botgento\Base\Helper\Data');

$moduleEnable = $helper->getModuleIsEnableAndValid();
$instockEnable = $helper->getConfig(\Botgento\Base\Helper\Data::INSTOCK_ENABLE);

if ($moduleEnable && $instockEnable) {

    $product = $block->getProduct();

    $output = $helper->genBGCValue();

    if (!empty($product) && !$product->isAvailable()) {
    ?>
        <div class="botgento-instock-alert">
            <p class="botgento-instock-alert-text"><?php echo __('Notify me when this product is back in stock'); ?></p>
            <div id="fb-loader" class="fb-loader" style="clear: both">
                <img src="<?php echo $this->getViewFileUrl('Botgento_Base::images/fb-loader.gif'); ?>"
                     alt="<?php echo __('Please wait...'); ?>"
                     title="<?php echo __('Please wait...'); ?>"
                     class="v-middle" width="30px">
            </div>
            <div class="fb-send-to-messenger text-center"
                 messenger_app_id="<?php echo $helper->getConfig(\Botgento\Base\Helper\Data::APP_ID) ?>"
                 page_id="<?php echo $helper->getConfig(\Botgento\Base\Helper\Data::PAGE_ID) ?>"
                 data-ref="INSTOCK_<?php echo $output; ?>"
                 color="<?php echo $helper->getConfig(\Botgento\Base\Helper\Data::INSTOCK_BUTTON_COLOR) ?>"
                 cta_text="<?php echo $helper->getConfig(\Botgento\Base\Helper\Data::INSTOCK_BUTTON_TEXT) ?>"
                 size="<?php echo $helper->getConfig(\Botgento\Base\Helper\Data::INSTOCK_BUTTON_SIZE) ?>">
            </div>
        </div>
        <script type="text/javascript">
            var scriptLoad = (function() {
              function _load(tag) {
                return function(url) {
                  // This promise will be used by Promise.all to determine success or failure
                  return new Promise(function(resolve, reject) {
                    var element = document.createElement(tag);
                    var parent = 'body';
                    var attr = 'src';

                    // Important success and error for the promise
                    element.onload = function() {
                      resolve(url);
                    };
                    element.onerror = function() {
                      reject(url);
                    };

                    // Need to set different attributes depending on tag type
                    switch(tag) {
                      case 'script':
                        element.async = true;
                        break;
                      case 'link':
                        element.type = 'text/css';
                        element.rel = 'stylesheet';
                        attr = 'href';
                        parent = 'head';
                    }

                    // Inject into document to kick off loading
                    element[attr] = url;
                    document[parent].appendChild(element);
                  });
                };
              }
              
              return {
                css: _load('link'),
                js: _load('script'),
                img: _load('img')
              }
            })();
            require(['jquery'], function ($) {
                $(document).ready(renderedFBBtn);

                function renderedFBBtn() {

                    Promise.all([
                      scriptLoad.js('https://connect.facebook.net/en_US/sdk.js'), 
                      //load.css('lib/highlighter.css'),
                      //load.img('images/logo.png')
                    ]).then(function() {
                      FB.init({
                            appId: '<?php echo $helper->getConfig(\Botgento\Base\Helper\Data::APP_ID) ?>',
                            autoLogAppEvents: true,
                            xfbml: true,
                            version: 'v3.0'
                      });
                      FB.Event.subscribe('send_to_messenger', function (e) {
                          if (e.event == 'rendered') {
                                document.getElementById("fb-loader").style.display = "none";
                            }
                            // callback for events triggered by the plugin
                            if (e.event == 'opt_in') {
                                $.ajax({
                                    url: "<?php echo $this->getUrl('botgento/instock/alert');?>",
                                    data: {
                                        product_id: "<?php echo $product->getId() ?>",
                                        uuid: "<?php echo $helper->getUuid() ?>"
                                    },
                                    success: function (xhr) {
                                        // console.log(xhr);
                                    }
                                });
                            }
                      });
                    }).catch(function() {
                      console.log('Oh no, epic failure!');
                    });

                }
            });
        </script>
<?php

    }
}

?>
