<?php
/**
 * @author Botgento Team
 * @copyright Copyright (c) 2017 Botgento (https://www.botgento.com)
 * @package Botgento_Base
 */

/**
 * Copyright © 2017 Botgento. All rights reserved.
 */
?>
<div style="background:#EAF0EE;border:1px solid #CCCCCC;margin-bottom:10px;padding:11px 0 0 10px;">
    <h4>
        <img width="280px" style="padding-left: 15px;" src="<?php echo $block->getViewFileUrl('Botgento_Base::images/botgento_logo.png') ?>"/><br><br>
        <div style="padding-left: 15px;">
            <p> <strong style="color:#EA7601;"><?php echo __('Botgento For Magento v') ?><?php echo $this->getModuleVersion() ?><?php echo __(' by') ?></strong> <a style="color:#EA7601;" target="_blank" href="https://aureatelabs.com/"><strong>Aureatelabs</strong></a></p>
            <p><?php echo __('For technical support visit our') ?> <a style="color:#EA7601;" href="https://support.botgento.com/" target="_blank"><?php echo __('Help Center') ?></a> <?php echo __('or email us at') ?> <a style="color:#EA7601;" href="mailto:support@botgento.com" target="_blank"><?php echo __('support@botgento.com') ?></a></p>
        </div>
    </h4>
</div>